/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { DunkinAboutFaqSection as DunkinDonutsComponentDunkinAboutFaqSection } from "./components/DunkinAboutFaqSection";
import { DunkinBreadcrumbSection as DunkinDonutsComponentDunkinBreadcrumbSection } from "./components/DunkinBreadcrumbSection";
import { DunkinFeaturedSection as DunkinDonutsComponentDunkinFeaturedSection } from "./components/DunkinFeaturedSection";
import { DunkinFooterSection as DunkinDonutsComponentDunkinFooterSection } from "./components/DunkinFooterSection";
import { DunkinHeaderSection as DunkinDonutsComponentDunkinHeaderSection } from "./components/DunkinHeaderSection";
import { DunkinHeroSection as DunkinDonutsComponentDunkinHeroSection } from "./components/DunkinHeroSection";
import { DunkinMealDealSection as DunkinDonutsComponentDunkinMealDealSection } from "./components/DunkinMealDealSection";
import { DunkinNearbyStoresSection as DunkinDonutsComponentDunkinNearbyStoresSection } from "./components/DunkinNearbyStoresSection";
import { DunkinRewardsSection as DunkinDonutsComponentDunkinRewardsSection } from "./components/DunkinRewardsSection";
import { DunkinVideoSection as DunkinDonutsComponentDunkinVideoSection } from "./components/DunkinVideoSection";

export const DunkinDonutsConfig: Config = {
  components: {
    DunkinAboutFaqSection: DunkinDonutsComponentDunkinAboutFaqSection,
    DunkinBreadcrumbSection: DunkinDonutsComponentDunkinBreadcrumbSection,
    DunkinFeaturedSection: DunkinDonutsComponentDunkinFeaturedSection,
    DunkinFooterSection: DunkinDonutsComponentDunkinFooterSection,
    DunkinHeaderSection: DunkinDonutsComponentDunkinHeaderSection,
    DunkinHeroSection: DunkinDonutsComponentDunkinHeroSection,
    DunkinMealDealSection: DunkinDonutsComponentDunkinMealDealSection,
    DunkinNearbyStoresSection: DunkinDonutsComponentDunkinNearbyStoresSection,
    DunkinRewardsSection: DunkinDonutsComponentDunkinRewardsSection,
    DunkinVideoSection: DunkinDonutsComponentDunkinVideoSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "DunkinAboutFaqSection",
        "DunkinBreadcrumbSection",
        "DunkinFeaturedSection",
        "DunkinFooterSection",
        "DunkinHeaderSection",
        "DunkinHeroSection",
        "DunkinMealDealSection",
        "DunkinNearbyStoresSection",
        "DunkinRewardsSection",
        "DunkinVideoSection",
      ],
    },
  },
};
