buildConfiguration:
  buildCommand: npm run build -- --reverse-proxy-prefix www.brand.com/locations
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
sitemap:
  excludeList:
    - edit
serving:
  reverseProxyPrefix: www.brand.com/locations
dynamicRoutes:
  - from: /assets/*
    to: /locations/assets/:splat
    status: 200
