buildConfiguration:
  buildCommand: npm run build -- ${YEXT_REVERSE_PROXY_PREFIX:+--reverse-proxy-prefix="$YEXT_REVERSE_PROXY_PREFIX"} --plugin-total-filesize-limit 15
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
sitemap:
  excludeList:
    - edit