/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.mjs */
import type { Config } from "@puckeditor/core";

import ComponentTestBannerSection from "../src/components/TestBannerSection";
import ComponentTestHeroSection from "../src/components/TestHeroSection";
import AtomCTASlot from "../src/atoms/CTASlot";
import AtomHeadingTextSlot from "../src/atoms/HeadingTextSlot";
import AtomHeroImageSlot from "../src/atoms/HeroImageSlot";
import AtomHoursStatusSlot from "../src/atoms/HoursStatusSlot";

export const mainConfig: Config = {
  components: {
    TestBannerSection: ComponentTestBannerSection,
    TestHeroSection: ComponentTestHeroSection,
    CTASlot: AtomCTASlot,
    HeadingTextSlot: AtomHeadingTextSlot,
    HeroImageSlot: AtomHeroImageSlot,
    HoursStatusSlot: AtomHoursStatusSlot,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "TestBannerSection",
        "TestHeroSection",
      ],
    },
    atoms: {
      title: "Atoms",
      components: [
        "CTASlot",
        "HeadingTextSlot",
        "HeroImageSlot",
        "HoursStatusSlot",
      ],
    },
  },
};

export default mainConfig;
