/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/style.css";
import "../index.css";
import {
  Template,
  GetPath,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
  TagType,
  TransformProps,
} from "@yext/pages";
import { Render, resolveAllData } from "@measured/puck";
import {
  applyTheme,
  VisualEditorProvider,
  getPageMetadata,
  applyAnalytics,
  applyHeaderScript,
  applyCertifiedFacts,
  migrate,
  migrationRegistry,
  filterComponentsFromConfig,
  resolvePageSetUrlTemplate,
  defaultThemeConfig,
  mainConfig,
  getSchema,
  getCanonicalUrl,
} from "@yext/visual-editor";
import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = (
  data: TemplateRenderProps
): HeadConfig => {
  const { document, relativePrefixToRoot } = data;
  const { title, description } = getPageMetadata(document);
  const schema = getSchema(data);
  const faviconUrl = document?._favicon ?? document?._site?.favicon?.url;

  return {
    title: title,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link" as TagType,
        attributes: {
          rel: "icon",
          type: "image/x-icon",
        },
      },
      ...(data.document.siteDomain
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "canonical",
                href: getCanonicalUrl(data),
              },
            },
          ]
        : []),
      ...(description
        ? [
            {
              type: "meta" as TagType,
              attributes: {
                name: "description",
                content: description,
              },
            },
          ]
        : []),
      ...(faviconUrl
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "icon",
                type: "image/x-icon",
                href: faviconUrl,
              },
            },
          ]
        : []),
    ],
    // other: [
    //   applyAnalytics(document),
    //   applyHeaderScript(document),
    //   applyTheme(document, relativePrefixToRoot, defaultThemeConfig),
    //   SchemaWrapper(schema),
    //   applyCertifiedFacts(document),
    // ].join("\n"),
  };
};

export const getPath: GetPath<TemplateProps> = ({
  document,
  relativePrefixToRoot,
}) => {
  return resolvePageSetUrlTemplate(document, relativePrefixToRoot);
};

export const transformProps: TransformProps<TemplateProps> = async (props) => {
  const { document } = props;

  const logDataSize = (label: string, data: any) => {
    const size = Buffer.byteLength(JSON.stringify(data)) / 1024 / 1024;
    console.log(`[Data Size - ${label}] approx ${size.toFixed(2)} MB`);
  };

  logDataSize("Before Migration", document);

  const migratedData = migrate(
    JSON.parse(document.__.layout),
    migrationRegistry,
    mainConfig,
    document
  );

  logDataSize("After Migration", migratedData);

  // const resolvedData = await resolveAllData(migratedData, mainConfig, {
  //   streamDocument: document,
  // });

  // logDataSize("After Data Resolution", resolvedData);

  return { ...props, data: migratedData };
};

const Location: Template<TemplateRenderProps> = (props) => {
  const { document, data } = props;
  // const filteredConfig = filterComponentsFromConfig(
  //   mainConfig,
  //   document?._additionalLayoutComponents,
  //   document?._additionalLayoutCategories
  // );

  return (
    <AnalyticsProvider
      apiKey={document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY}
      templateData={props}
      currency="USD"
    >
      <VisualEditorProvider templateProps={props}>
        <Render
          config={mainConfig}
          data={data}
          metadata={{ streamDocument: document }}
        />
      </VisualEditorProvider>
    </AnalyticsProvider>
  );
};

export default Location;
