/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/style.css";
import "../index.css";
import {
  Template,
  GetPath,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
  TagType,
  TransformProps,
} from "@yext/pages";
import { Render, resolveAllData } from "@measured/puck";
import {
  applyTheme,
  VisualEditorProvider,
  getPageMetadata,
  applyAnalytics,
  applyHeaderScript,
  migrate,
  migrationRegistry,
  filterComponentsFromConfig,
  resolvePageSetUrlTemplate,
  defaultThemeConfig,
  mainConfig,
  getSchema,
  getCanonicalUrl,
} from "@yext/visual-editor";
import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = (
  data: TemplateRenderProps
): HeadConfig => {
  console.log("start getHeadConfig");
  const { document, relativePrefixToRoot } = data;
  const { title, description } = getPageMetadata(document);
  const schema = getSchema(data);
  const faviconUrl = document?._favicon ?? document?._site?.favicon?.url;

  console.log("getHeadConfig checkpoint 1");
  const a: any = {
    title: title,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link" as TagType,
        attributes: {
          rel: "icon",
          type: "image/x-icon",
        },
      },
      ...(data.document.siteDomain
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "canonical",
                href: getCanonicalUrl(data),
              },
            },
          ]
        : []),
      ...(description
        ? [
            {
              type: "meta" as TagType,
              attributes: {
                name: "description",
                content: description,
              },
            },
          ]
        : []),
      ...(faviconUrl
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "icon",
                type: "image/x-icon",
                href: faviconUrl,
              },
            },
          ]
        : []),
    ],
    other: [
      applyAnalytics(document),
      applyHeaderScript(document),
      applyTheme(document, relativePrefixToRoot, defaultThemeConfig),
      SchemaWrapper(schema),
    ].join("\n"),
  };
  console.log("getHeadConfig checkpoint 2, returning");

  return a;
};

export const getPath: GetPath<TemplateProps> = ({
  document,
  relativePrefixToRoot,
}) => {
  console.log("getPath starting");

  const a = resolvePageSetUrlTemplate(document, relativePrefixToRoot);
  console.log("getPath returning");
  return a;
};

export const transformProps: TransformProps<TemplateProps> = async (props) => {
  console.log("transformProps starting");

  const { document } = props;
  const migratedData = migrate(
    JSON.parse(document.__.layout),
    migrationRegistry,
    mainConfig,
    document
  );
  const updatedData = await resolveAllData(migratedData, mainConfig, {
    streamDocument: document,
  });

  console.log("transformProps returning");
  return { ...props, data: updatedData };
};

const Location: Template<TemplateRenderProps> = (props) => {
  console.log("template start");
  const { document, data } = props;
  const filteredConfig = filterComponentsFromConfig(
    mainConfig,
    document?._additionalLayoutComponents,
    document?._additionalLayoutCategories
  );
  console.log("template checkpoint 1");

  const a = (
    <AnalyticsProvider
      apiKey={document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY}
      templateData={props}
      currency="USD"
    >
      <VisualEditorProvider templateProps={props}>
        <Render
          config={filteredConfig}
          data={data}
          metadata={{ streamDocument: document }}
        />
      </VisualEditorProvider>
    </AnalyticsProvider>
  );

  console.log("template checkpoint 2, returning");

  return a;
};

export default Location;
