/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/style.css";
import "../index.css";
import {
  Template,
  GetPath,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
  TagType,
  TransformProps,
} from "@yext/pages";
import { Render, resolveAllData } from "@measured/puck";
import {
  applyTheme,
  VisualEditorProvider,
  getPageMetadata,
  applyAnalytics,
  applyHeaderScript,
  migrate,
  migrationRegistry,
  filterComponentsFromConfig,
  resolveUrlTemplate,
  defaultThemeConfig,
  mainConfig,
  getSchema,
} from "@yext/visual-editor";
import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  document,
}): HeadConfig => {
  const { title, description } = getPageMetadata(document);
  const schema = getSchema(document);
  const faviconUrl = document?._favicon ?? document?._site?.favicon?.url;

  return {
    title: title,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
        },
      },
      ...(description
        ? [
            {
              type: "meta" as TagType,
              attributes: {
                name: "description",
                content: description,
              },
            },
          ]
        : []),
      ...(faviconUrl
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "icon",
                type: "image/x-icon",
                href: faviconUrl,
              },
            },
          ]
        : []),
    ],
    other: [
      applyAnalytics(document),
      applyHeaderScript(document),
      applyTheme(document, defaultThemeConfig),
      SchemaWrapper(schema),
    ].join("\n"),
  };
};

export const getPath: GetPath<TemplateProps> = ({
  document,
  relativePrefixToRoot,
}) => {
  return resolveUrlTemplate(document, relativePrefixToRoot);
};

export const transformProps: TransformProps<TemplateProps> = async (props) => {
  const { document } = props;
  console.log("pre migrate layout", document.__.layout);
  const migratedData = migrate(
    JSON.parse(document.__.layout),
    migrationRegistry,
    mainConfig,
    document
  );
  const updatedData = await resolveAllData(migratedData, mainConfig, {
    document,
  });
  console.log("post migrate layout", JSON.stringify(updatedData));

  return { ...props, data: updatedData };
};

const Location: Template<TemplateRenderProps> = (props) => {
  const { document, data } = props;
  const filteredConfig = filterComponentsFromConfig(
    mainConfig,
    document?._additionalLayoutComponents,
    document?._additionalLayoutCategories
  );

  console.log("passing data into main", JSON.stringify(data));
  return (
    <AnalyticsProvider
      apiKey={document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY}
      templateData={props}
      currency="USD"
    >
      <VisualEditorProvider templateProps={props}>
        <Render
          config={filteredConfig}
          data={data}
          metadata={{ streamDocument: document }}
        />
      </VisualEditorProvider>
    </AnalyticsProvider>
  );
};

export default Location;
