/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { SweetgreenFaqSection as MainComponentSweetgreenFaqSection } from "./components/SweetgreenFaqSection";
import { SweetgreenFindUsSection as MainComponentSweetgreenFindUsSection } from "./components/SweetgreenFindUsSection";
import { SweetgreenFooterSection as MainComponentSweetgreenFooterSection } from "./components/SweetgreenFooterSection";
import { SweetgreenLocationHeroSection as MainComponentSweetgreenLocationHeroSection } from "./components/SweetgreenLocationHeroSection";
import { SweetgreenMenuSection as MainComponentSweetgreenMenuSection } from "./components/SweetgreenMenuSection";
import { SweetgreenPromoCardsSection as MainComponentSweetgreenPromoCardsSection } from "./components/SweetgreenPromoCardsSection";
import { SweetgreenRequestLocationSection as MainComponentSweetgreenRequestLocationSection } from "./components/SweetgreenRequestLocationSection";
import { SweetgreenSiteHeaderSection as MainComponentSweetgreenSiteHeaderSection } from "./components/SweetgreenSiteHeaderSection";
import { SweetgreenSustainabilitySection as MainComponentSweetgreenSustainabilitySection } from "./components/SweetgreenSustainabilitySection";

export const MainConfig: Config = {
  components: {
    SweetgreenFaqSection: MainComponentSweetgreenFaqSection,
    SweetgreenFindUsSection: MainComponentSweetgreenFindUsSection,
    SweetgreenFooterSection: MainComponentSweetgreenFooterSection,
    SweetgreenLocationHeroSection: MainComponentSweetgreenLocationHeroSection,
    SweetgreenMenuSection: MainComponentSweetgreenMenuSection,
    SweetgreenPromoCardsSection: MainComponentSweetgreenPromoCardsSection,
    SweetgreenRequestLocationSection:
      MainComponentSweetgreenRequestLocationSection,
    SweetgreenSiteHeaderSection: MainComponentSweetgreenSiteHeaderSection,
    SweetgreenSustainabilitySection:
      MainComponentSweetgreenSustainabilitySection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "SweetgreenFaqSection",
        "SweetgreenFindUsSection",
        "SweetgreenFooterSection",
        "SweetgreenLocationHeroSection",
        "SweetgreenMenuSection",
        "SweetgreenPromoCardsSection",
        "SweetgreenRequestLocationSection",
        "SweetgreenSiteHeaderSection",
        "SweetgreenSustainabilitySection",
      ],
    },
    other: { title: "Other", visible: false, components: [] },
  },
};
