/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { YetiCustomizeBannerSection as MainComponentYetiCustomizeBannerSection } from "./components/YetiCustomizeBannerSection";
import { YetiExploreStoreSection as MainComponentYetiExploreStoreSection } from "./components/YetiExploreStoreSection";
import { YetiFaqSection as MainComponentYetiFaqSection } from "./components/YetiFaqSection";
import { YetiFooterSection as MainComponentYetiFooterSection } from "./components/YetiFooterSection";
import { YetiHeaderSection as MainComponentYetiHeaderSection } from "./components/YetiHeaderSection";
import { YetiHeroSection as MainComponentYetiHeroSection } from "./components/YetiHeroSection";
import { YetiHoursLocationSection as MainComponentYetiHoursLocationSection } from "./components/YetiHoursLocationSection";
import { YetiReservationBannerSection as MainComponentYetiReservationBannerSection } from "./components/YetiReservationBannerSection";

export const MainConfig: Config = {
  components: {
    YetiCustomizeBannerSection: MainComponentYetiCustomizeBannerSection,
    YetiExploreStoreSection: MainComponentYetiExploreStoreSection,
    YetiFaqSection: MainComponentYetiFaqSection,
    YetiFooterSection: MainComponentYetiFooterSection,
    YetiHeaderSection: MainComponentYetiHeaderSection,
    YetiHeroSection: MainComponentYetiHeroSection,
    YetiHoursLocationSection: MainComponentYetiHoursLocationSection,
    YetiReservationBannerSection: MainComponentYetiReservationBannerSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "YetiCustomizeBannerSection",
        "YetiExploreStoreSection",
        "YetiFaqSection",
        "YetiFooterSection",
        "YetiHeaderSection",
        "YetiHeroSection",
        "YetiHoursLocationSection",
        "YetiReservationBannerSection",
      ],
    },
  },
};
