/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { DunkinAboutFaqSection as MainComponentDunkinAboutFaqSection } from "./DunkinAboutFaqSection";
import { DunkinBreadcrumbSection as MainComponentDunkinBreadcrumbSection } from "./DunkinBreadcrumbSection";
import { DunkinFeaturedSection as MainComponentDunkinFeaturedSection } from ".//DunkinFeaturedSection";
import { DunkinFooterSection as MainComponentDunkinFooterSection } from "./DunkinFooterSection";
import { DunkinHeaderSection as MainComponentDunkinHeaderSection } from "./DunkinHeaderSection";
import { DunkinHeroSection as MainComponentDunkinHeroSection } from "./DunkinHeroSection";
import { DunkinMealDealSection as MainComponentDunkinMealDealSection } from "./DunkinMealDealSection";
import { DunkinNearbyStoresSection as MainComponentDunkinNearbyStoresSection } from "./DunkinNearbyStoresSection";
import { DunkinRewardsSection as MainComponentDunkinRewardsSection } from "./DunkinRewardsSection";
import { DunkinVideoSection as MainComponentDunkinVideoSection } from "./DunkinVideoSection";

export const DunkinConfig: Config = {
  components: {
    DunkinAboutFaqSection: MainComponentDunkinAboutFaqSection,
    DunkinBreadcrumbSection: MainComponentDunkinBreadcrumbSection,
    DunkinFeaturedSection: MainComponentDunkinFeaturedSection,
    DunkinFooterSection: MainComponentDunkinFooterSection,
    DunkinHeaderSection: MainComponentDunkinHeaderSection,
    DunkinHeroSection: MainComponentDunkinHeroSection,
    DunkinMealDealSection: MainComponentDunkinMealDealSection,
    DunkinNearbyStoresSection: MainComponentDunkinNearbyStoresSection,
    DunkinRewardsSection: MainComponentDunkinRewardsSection,
    DunkinVideoSection: MainComponentDunkinVideoSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "DunkinAboutFaqSection",
        "DunkinBreadcrumbSection",
        "DunkinFeaturedSection",
        "DunkinFooterSection",
        "DunkinHeaderSection",
        "DunkinHeroSection",
        "DunkinMealDealSection",
        "DunkinNearbyStoresSection",
        "DunkinRewardsSection",
        "DunkinVideoSection",
      ],
    },
    other: { title: "Other", visible: false, components: [] },
  },
};