import * as React from "react";
import type { PuckComponent } from "@puckeditor/core";
import { VisibilityWrapper, type YextComponentConfig, type YextFields } from "@yext/visual-editor";
import { AnalyticsScopeProvider, Link } from "@yext/pages-components";

type EdwardJonesPagesContactProps = { heading: string; description: string; cta: { label: string; link: string }; section: { backgroundColor: string; visibleOnLivePage: boolean } };
const fields: YextFields<EdwardJonesPagesContactProps> = { heading: { label: "Heading", type: "text" }, description: { label: "Description", type: "textarea" }, cta: { label: "Call To Action", type: "object", objectFields: { label: { label: "Label", type: "text" }, link: { label: "Link", type: "text" } } }, section: { label: "Section", type: "object", objectFields: { backgroundColor: { label: "Background Color", type: "text" }, visibleOnLivePage: { label: "Visible On Live Page", type: "radio", options: [{ label: "Yes", value: true }, { label: "No", value: false }] } } } };
const Contact: PuckComponent<EdwardJonesPagesContactProps> = (props) => <VisibilityWrapper liveVisibility={props.section.visibleOnLivePage} isEditing={props.puck.isEditing}><AnalyticsScopeProvider name="EdwardJonesPagesContact"><section id="contact" className="px-6 py-20 text-white md:px-10" style={{ backgroundColor: props.section.backgroundColor }}><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div className="max-w-3xl"><h2 className="text-4xl font-semibold tracking-tight md:text-5xl">{props.heading}</h2><p className="mt-4 text-lg leading-8 text-white/85">{props.description}</p></div><Link className="shrink-0 rounded-full bg-white px-6 py-3 font-bold text-[#004b3b]" cta={{ link: props.cta.link, linkType: "URL" }} eventName="contactCta">{props.cta.label}</Link></div></section></AnalyticsScopeProvider></VisibilityWrapper>;
export const EdwardJonesPagesContact: YextComponentConfig<EdwardJonesPagesContactProps> = { label: "Contact", fields, defaultProps: { heading: "A conversation can be a powerful first step.", description: "Connect with an advisor to talk about where you are today and where you want to go next.", cta: { label: "Get Started", link: "#" }, section: { backgroundColor: "#006b54", visibleOnLivePage: true } }, render: (props) => <Contact {...props} /> };
