import * as React from "react";
import type { PuckComponent } from "@puckeditor/core";
import { VisibilityWrapper, type YextComponentConfig, type YextFields } from "@yext/visual-editor";
import { AnalyticsScopeProvider, Link } from "@yext/pages-components";

type FooterLink = { label: string; link: string };
type EdwardJonesPagesFooterProps = { brandName: string; legalText: string; links: FooterLink[]; section: { backgroundColor: string; visibleOnLivePage: boolean } };
const fields: YextFields<EdwardJonesPagesFooterProps> = { brandName: { label: "Brand Name", type: "text" }, legalText: { label: "Legal Text", type: "textarea" }, links: { label: "Footer Links", type: "array", arrayFields: { label: { label: "Label", type: "text" }, link: { label: "Link", type: "text" } }, defaultItemProps: { label: "New Link", link: "#" }, getItemSummary: (item) => item.label }, section: { label: "Section", type: "object", objectFields: { backgroundColor: { label: "Background Color", type: "text" }, visibleOnLivePage: { label: "Visible On Live Page", type: "radio", options: [{ label: "Yes", value: true }, { label: "No", value: false }] } } } };
const Footer: PuckComponent<EdwardJonesPagesFooterProps> = (props) => <VisibilityWrapper liveVisibility={props.section.visibleOnLivePage} isEditing={props.puck.isEditing}><AnalyticsScopeProvider name="EdwardJonesPagesFooter"><footer className="px-6 py-10 text-white md:px-10" style={{ backgroundColor: props.section.backgroundColor }}><div className="mx-auto flex max-w-7xl flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><p className="text-xl font-bold">{props.brandName}</p><p className="mt-3 max-w-xl text-sm leading-6 text-white/70">{props.legalText}</p></div><nav aria-label="Footer navigation" className="flex flex-wrap gap-x-5 gap-y-3 text-sm">{props.links.map((item, index) => <Link key={`${item.label}-${index}`} cta={{ link: item.link, linkType: "URL" }} eventName={`footerLink${index}`}>{item.label}</Link>)}</nav></div></footer></AnalyticsScopeProvider></VisibilityWrapper>;
export const EdwardJonesPagesFooter: YextComponentConfig<EdwardJonesPagesFooterProps> = { label: "Footer", fields, defaultProps: { brandName: "Edward Jones", legalText: "This sample template is designed for editorial customization. Replace this copy with your approved disclosures and legal language.", links: [{ label: "Privacy", link: "#" }, { label: "Accessibility", link: "#" }, { label: "Disclosures", link: "#" }], section: { backgroundColor: "#10261e", visibleOnLivePage: true } }, render: (props) => <Footer {...props} /> };
