/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */
import type { Config } from "@puckeditor/core";
import { mainConfig, type MainConfigProps } from "@yext/visual-editor";
import { YextElevatedWoodfireAboutSection as YextElevatedWoodfireComponentYextElevatedWoodfireAboutSection } from "./components/yext-ElevatedWoodfireAboutSection";
import { YextElevatedWoodfireDetailsSection as YextElevatedWoodfireComponentYextElevatedWoodfireDetailsSection } from "./components/yext-ElevatedWoodfireDetailsSection";
import { YextElevatedWoodfireEventSection as YextElevatedWoodfireComponentYextElevatedWoodfireEventSection } from "./components/yext-ElevatedWoodfireEventSection";
import { YextElevatedWoodfireFaqSection as YextElevatedWoodfireComponentYextElevatedWoodfireFaqSection } from "./components/yext-ElevatedWoodfireFaqSection";
import { YextElevatedWoodfireFeaturedItemsSection as YextElevatedWoodfireComponentYextElevatedWoodfireFeaturedItemsSection } from "./components/yext-ElevatedWoodfireFeaturedItemsSection";
import { YextElevatedWoodfireFindUsSection as YextElevatedWoodfireComponentYextElevatedWoodfireFindUsSection } from "./components/yext-ElevatedWoodfireFindUsSection";
import { YextElevatedWoodfireFooterSection as YextElevatedWoodfireComponentYextElevatedWoodfireFooterSection } from "./components/yext-ElevatedWoodfireFooterSection";
import { YextElevatedWoodfireHeaderSection as YextElevatedWoodfireComponentYextElevatedWoodfireHeaderSection } from "./components/yext-ElevatedWoodfireHeaderSection";
import { YextElevatedWoodfireHeroSection as YextElevatedWoodfireComponentYextElevatedWoodfireHeroSection } from "./components/yext-ElevatedWoodfireHeroSection";
import { YextElevatedWoodfireOfferingsSection as YextElevatedWoodfireComponentYextElevatedWoodfireOfferingsSection } from "./components/yext-ElevatedWoodfireOfferingsSection";
import { YextElevatedWoodfireReviewsSection as YextElevatedWoodfireComponentYextElevatedWoodfireReviewsSection } from "./components/yext-ElevatedWoodfireReviewsSection";
type GeneratedYextElevatedWoodfireConfigProps = Pick<MainConfigProps, "MainContent"> & {
  "YextElevatedWoodfireAboutSection": any;
  "YextElevatedWoodfireDetailsSection": any;
  "YextElevatedWoodfireEventSection": any;
  "YextElevatedWoodfireFaqSection": any;
  "YextElevatedWoodfireFeaturedItemsSection": any;
  "YextElevatedWoodfireFindUsSection": any;
  "YextElevatedWoodfireFooterSection": any;
  "YextElevatedWoodfireHeaderSection": any;
  "YextElevatedWoodfireHeroSection": any;
  "YextElevatedWoodfireOfferingsSection": any;
  "YextElevatedWoodfireReviewsSection": any;
};
export const YextElevatedWoodfireConfig: Config<GeneratedYextElevatedWoodfireConfigProps> = {
  components: {
    "MainContent": mainConfig.components.MainContent,
    "YextElevatedWoodfireAboutSection": YextElevatedWoodfireComponentYextElevatedWoodfireAboutSection,
    "YextElevatedWoodfireDetailsSection": YextElevatedWoodfireComponentYextElevatedWoodfireDetailsSection,
    "YextElevatedWoodfireEventSection": YextElevatedWoodfireComponentYextElevatedWoodfireEventSection,
    "YextElevatedWoodfireFaqSection": YextElevatedWoodfireComponentYextElevatedWoodfireFaqSection,
    "YextElevatedWoodfireFeaturedItemsSection": YextElevatedWoodfireComponentYextElevatedWoodfireFeaturedItemsSection,
    "YextElevatedWoodfireFindUsSection": YextElevatedWoodfireComponentYextElevatedWoodfireFindUsSection,
    "YextElevatedWoodfireFooterSection": YextElevatedWoodfireComponentYextElevatedWoodfireFooterSection,
    "YextElevatedWoodfireHeaderSection": YextElevatedWoodfireComponentYextElevatedWoodfireHeaderSection,
    "YextElevatedWoodfireHeroSection": YextElevatedWoodfireComponentYextElevatedWoodfireHeroSection,
    "YextElevatedWoodfireOfferingsSection": YextElevatedWoodfireComponentYextElevatedWoodfireOfferingsSection,
    "YextElevatedWoodfireReviewsSection": YextElevatedWoodfireComponentYextElevatedWoodfireReviewsSection,
  },
  categories: {
  "structure": {
    "components": [
      "MainContent"
    ],
    "visible": false,
    "title": "Structure"
  },
  "components": {
    "title": "Components",
    "components": [
      "YextElevatedWoodfireAboutSection",
      "YextElevatedWoodfireDetailsSection",
      "YextElevatedWoodfireEventSection",
      "YextElevatedWoodfireFaqSection",
      "YextElevatedWoodfireFeaturedItemsSection",
      "YextElevatedWoodfireFindUsSection",
      "YextElevatedWoodfireFooterSection",
      "YextElevatedWoodfireHeaderSection",
      "YextElevatedWoodfireHeroSection",
      "YextElevatedWoodfireOfferingsSection",
      "YextElevatedWoodfireReviewsSection"
    ]
  },
  "other": {
    "title": "Other",
    "visible": false,
    "components": []
  }
},
};