/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { DunkinAboutFaqSection as MainComponentDunkinAboutFaqSection } from "./components/DunkinAboutFaqSection";
import { DunkinBreadcrumbSection as MainComponentDunkinBreadcrumbSection } from "./components/DunkinBreadcrumbSection";
import { DunkinFeaturedSection as MainComponentDunkinFeaturedSection } from "./components/DunkinFeaturedSection";
import { DunkinFooterSection as MainComponentDunkinFooterSection } from "./components/DunkinFooterSection";
import { DunkinHeaderSection as MainComponentDunkinHeaderSection } from "./components/DunkinHeaderSection";
import { DunkinHeroSection as MainComponentDunkinHeroSection } from "./components/DunkinHeroSection";
import { DunkinMealDealSection as MainComponentDunkinMealDealSection } from "./components/DunkinMealDealSection";
import { DunkinNearbyStoresSection as MainComponentDunkinNearbyStoresSection } from "./components/DunkinNearbyStoresSection";
import { DunkinRewardsSection as MainComponentDunkinRewardsSection } from "./components/DunkinRewardsSection";
import { DunkinVideoSection as MainComponentDunkinVideoSection } from "./components/DunkinVideoSection";

export const DunkinConfig: Config = {
  components: {
    DunkinAboutFaqSection: MainComponentDunkinAboutFaqSection,
    DunkinBreadcrumbSection: MainComponentDunkinBreadcrumbSection,
    DunkinFeaturedSection: MainComponentDunkinFeaturedSection,
    DunkinFooterSection: MainComponentDunkinFooterSection,
    DunkinHeaderSection: MainComponentDunkinHeaderSection,
    DunkinHeroSection: MainComponentDunkinHeroSection,
    DunkinMealDealSection: MainComponentDunkinMealDealSection,
    DunkinNearbyStoresSection: MainComponentDunkinNearbyStoresSection,
    DunkinRewardsSection: MainComponentDunkinRewardsSection,
    DunkinVideoSection: MainComponentDunkinVideoSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "DunkinAboutFaqSection",
        "DunkinBreadcrumbSection",
        "DunkinFeaturedSection",
        "DunkinFooterSection",
        "DunkinHeaderSection",
        "DunkinHeroSection",
        "DunkinMealDealSection",
        "DunkinNearbyStoresSection",
        "DunkinRewardsSection",
        "DunkinVideoSection",
      ],
    },
    other: { title: "Other", visible: false, components: [] },
  },
};
