/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.ts */
import type { Config } from "@puckeditor/core";

import { DunkinAboutFaqSection as DunkinComponentDunkinAboutFaqSection } from "./components/DunkinAboutFaqSection";
import { DunkinBreadcrumbSection as DunkinComponentDunkinBreadcrumbSection } from "./components/DunkinBreadcrumbSection";
import { DunkinFeaturedSection as DunkinComponentDunkinFeaturedSection } from "./components/DunkinFeaturedSection";
import { DunkinFooterSection as DunkinComponentDunkinFooterSection } from "./components/DunkinFooterSection";
import { DunkinHeaderSection as DunkinComponentDunkinHeaderSection } from "./components/DunkinHeaderSection";
import { DunkinHeroSection as DunkinComponentDunkinHeroSection } from "./components/DunkinHeroSection";
import { DunkinMealDealSection as DunkinComponentDunkinMealDealSection } from "./components/DunkinMealDealSection";
import { DunkinNearbyStoresSection as DunkinComponentDunkinNearbyStoresSection } from "./components/DunkinNearbyStoresSection";
import { DunkinRewardsSection as DunkinComponentDunkinRewardsSection } from "./components/DunkinRewardsSection";
import { DunkinVideoSection as DunkinComponentDunkinVideoSection } from "./components/DunkinVideoSection";

export const DunkinConfig: Config = {
  components: {
    DunkinAboutFaqSection: DunkinComponentDunkinAboutFaqSection,
    DunkinBreadcrumbSection: DunkinComponentDunkinBreadcrumbSection,
    DunkinFeaturedSection: DunkinComponentDunkinFeaturedSection,
    DunkinFooterSection: DunkinComponentDunkinFooterSection,
    DunkinHeaderSection: DunkinComponentDunkinHeaderSection,
    DunkinHeroSection: DunkinComponentDunkinHeroSection,
    DunkinMealDealSection: DunkinComponentDunkinMealDealSection,
    DunkinNearbyStoresSection: DunkinComponentDunkinNearbyStoresSection,
    DunkinRewardsSection: DunkinComponentDunkinRewardsSection,
    DunkinVideoSection: DunkinComponentDunkinVideoSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "DunkinAboutFaqSection",
        "DunkinBreadcrumbSection",
        "DunkinFeaturedSection",
        "DunkinFooterSection",
        "DunkinHeaderSection",
        "DunkinHeroSection",
        "DunkinMealDealSection",
        "DunkinNearbyStoresSection",
        "DunkinRewardsSection",
        "DunkinVideoSection",
      ],
    },
    other: { title: "Other", visible: false, components: [] },
  },
};
