/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.mjs */
import type { Config } from "@puckeditor/core";

import DunkinComponentDunkinAboutFaqSection from "./components/DunkinAboutFaqSection";
import DunkinComponentDunkinBreadcrumbSection from "./components/DunkinBreadcrumbSection";
import DunkinComponentDunkinFeaturedSection from "./components/DunkinFeaturedSection";
import DunkinComponentDunkinFooterSection from "./components/DunkinFooterSection";
import DunkinComponentDunkinHeaderSection from "./components/DunkinHeaderSection";
import DunkinComponentDunkinHeroSection from "./components/DunkinHeroSection";
import DunkinComponentDunkinMealDealSection from "./components/DunkinMealDealSection";
import DunkinComponentDunkinNearbyStoresSection from "./components/DunkinNearbyStoresSection";
import DunkinComponentDunkinRewardsSection from "./components/DunkinRewardsSection";
import DunkinComponentDunkinVideoSection from "./components/DunkinVideoSection";

export const mainConfig: Config = {
  components: {
    DunkinAboutFaqSection: DunkinComponentDunkinAboutFaqSection,
    DunkinBreadcrumbSection: DunkinComponentDunkinBreadcrumbSection,
    DunkinFeaturedSection: DunkinComponentDunkinFeaturedSection,
    DunkinFooterSection: DunkinComponentDunkinFooterSection,
    DunkinHeaderSection: DunkinComponentDunkinHeaderSection,
    DunkinHeroSection: DunkinComponentDunkinHeroSection,
    DunkinMealDealSection: DunkinComponentDunkinMealDealSection,
    DunkinNearbyStoresSection: DunkinComponentDunkinNearbyStoresSection,
    DunkinRewardsSection: DunkinComponentDunkinRewardsSection,
    DunkinVideoSection: DunkinComponentDunkinVideoSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "DunkinAboutFaqSection",
        "DunkinBreadcrumbSection",
        "DunkinFeaturedSection",
        "DunkinFooterSection",
        "DunkinHeaderSection",
        "DunkinHeroSection",
        "DunkinMealDealSection",
        "DunkinNearbyStoresSection",
        "DunkinRewardsSection",
        "DunkinVideoSection",
      ],
    },
  },
};

export default mainConfig;
