import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { migrateBuiltInTemplate } from "./migrateBuiltInTemplate.js";

const TODO_DISPLAY_NAME = "TODO: Add a display name.";
const TODO_DESCRIPTION = "TODO: Add a description.";

type Fixture = {
  root: string;
  sourceDirectory: string;
  libraryDirectory: string;
};

type FixtureOptions = {
  template?: Record<string, unknown>;
  layout?: unknown;
  components?: Record<string, string>;
  libraryFiles?: Record<string, string>;
};

type ValidationCase = FixtureOptions & {
  name: string;
  setup?: (fixture: Fixture) => void;
  error: RegExp;
};

/** Creates one isolated legacy-template fixture for a conversion test. */
const createFixture = ({
  template = {},
  layout = { content: [{ type: "Hero", props: {} }] },
  components = { "Hero.tsx": "export const Hero = () => <div />;\n" },
  libraryFiles = {},
}: FixtureOptions = {}): Fixture => {
  const root = fs.mkdtempSync(
    path.join(os.tmpdir(), "section-library-migration-"),
  );
  const sourceDirectory = path.join(root, "src", "registry", "example");
  const componentsDirectory = path.join(sourceDirectory, "components");
  fs.mkdirSync(componentsDirectory, { recursive: true });
  fs.writeFileSync(
    path.join(sourceDirectory, "template.json"),
    JSON.stringify({
      displayName: "Example Template",
      description: "Example description",
      previewImageUrl: "https://example.com/preview.png",
      previewSiteUrl: "",
      verticals: ["RETAIL"],
      purposes: ["LOCATION"],
      isBuiltIn: true,
      ...template,
    }),
  );
  fs.writeFileSync(
    path.join(sourceDirectory, "defaultLayout.json"),
    JSON.stringify(layout),
  );
  for (const [fileName, content] of Object.entries(components)) {
    const filePath = path.join(componentsDirectory, fileName);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
  }
  for (const [relativePath, content] of Object.entries(libraryFiles)) {
    const filePath = path.join(root, "src", "library", relativePath);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
  }
  return {
    root,
    sourceDirectory,
    libraryDirectory: path.join(root, "src", "library"),
  };
};

const removeFixture = (fixture: Fixture): void => {
  fs.rmSync(fixture.root, { recursive: true, force: true });
};

test("when dry run then it reports the conversion without changing files", (t) => {
  const fixture = createFixture({
    libraryFiles: {
      ".generated/libraryConfig.tsx":
        "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */\n",
    },
  });
  t.after(() => removeFixture(fixture));
  const output: string[] = [];

  migrateBuiltInTemplate({
    templateId: "example",
    rootDirectory: fixture.root,
    apply: false,
    write: (message) => output.push(message),
  });

  assert.equal(fs.existsSync(fixture.sourceDirectory), true);
  assert.equal(
    fs.readFileSync(
      path.join(fixture.libraryDirectory, ".generated", "libraryConfig.tsx"),
      "utf8",
    ),
    "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */\n",
  );
  assert.match(output.join("\n"), /Dry run: no files changed/);
  assert.match(output.join("\n"), /Manual follow-up work/);
});

test("when apply then it creates the Section Library and removes the legacy template", (t) => {
  const fixture = createFixture();
  t.after(() => removeFixture(fixture));

  migrateBuiltInTemplate({
    templateId: "example",
    rootDirectory: fixture.root,
    apply: true,
    write: () => {},
  });

  assert.equal(fs.existsSync(fixture.sourceDirectory), false);
  assert.deepEqual(
    JSON.parse(
      fs.readFileSync(
        path.join(fixture.libraryDirectory, "library.json"),
        "utf8",
      ),
    ),
    {
      schemaVersion: 1,
      id: "example",
      displayName: "Example Template",
      description: "Example description",
    },
  );
  assert.deepEqual(
    JSON.parse(
      fs.readFileSync(
        path.join(
          fixture.libraryDirectory,
          "layouts",
          "example",
          "metadata.json",
        ),
        "utf8",
      ),
    ),
    {
      id: "example",
      displayName: "Example Template",
      previewImageUrl: "https://example.com/preview.png",
      vertical: "RETAIL",
      purpose: "LOCATION",
      pageSetType: "ENTITY",
    },
  );
  assert.deepEqual(
    JSON.parse(
      fs.readFileSync(
        path.join(
          fixture.libraryDirectory,
          "layouts",
          "example",
          "defaultLayout.json",
        ),
        "utf8",
      ),
    ),
    { content: [{ type: "Hero", props: {} }] },
  );
  assert.match(
    fs.readFileSync(
      path.join(fixture.libraryDirectory, "sections", "Hero.tsx"),
      "utf8",
    ),
    /export const config: SectionConfig = \{\n  displayName: "TODO: Add a section display name\."/,
  );
});

test("when metadata is empty or ambiguous then it writes TODO values", (t) => {
  const fixture = createFixture({
    template: {
      displayName: "",
      description: "",
      previewImageUrl: "",
      verticals: ["RETAIL", "FOOD_AND_DINING"],
      purposes: [],
    },
  });
  t.after(() => removeFixture(fixture));

  migrateBuiltInTemplate({
    templateId: "example",
    rootDirectory: fixture.root,
    apply: true,
    write: () => {},
  });

  assert.deepEqual(
    JSON.parse(
      fs.readFileSync(
        path.join(fixture.libraryDirectory, "library.json"),
        "utf8",
      ),
    ),
    {
      schemaVersion: 1,
      id: "example",
      displayName: TODO_DISPLAY_NAME,
      description: TODO_DESCRIPTION,
    },
  );
  assert.deepEqual(
    JSON.parse(
      fs.readFileSync(
        path.join(
          fixture.libraryDirectory,
          "layouts",
          "example",
          "metadata.json",
        ),
        "utf8",
      ),
    ),
    {
      id: "example",
      displayName: TODO_DISPLAY_NAME,
      previewImageUrl: "TODO: Add a preview image URL.",
      vertical: "TODO: Choose one vertical.",
      purpose: "TODO: Choose one purpose.",
      pageSetType: "ENTITY",
    },
  );
});

test("when section IDs collide then it fails before changing files", (t) => {
  const fixture = createFixture();
  t.after(() => removeFixture(fixture));
  const componentsDirectory = path.join(fixture.sourceDirectory, "components");
  const readDirectory = fs.readdirSync;
  const readFile = fs.readFileSync;
  fs.readdirSync = ((directory: fs.PathLike, options?: unknown) => {
    const entries = readDirectory(
      directory,
      options as { withFileTypes: true },
    );
    if (directory !== componentsDirectory) {
      return entries;
    }
    return [
      ...entries,
      { name: "hero.tsx", isDirectory: () => false, isFile: () => true },
    ];
  }) as typeof fs.readdirSync;
  fs.readFileSync = ((filePath: fs.PathOrFileDescriptor, options?: unknown) =>
    filePath === path.join(componentsDirectory, "hero.tsx")
      ? "export const hero = () => <div />;\n"
      : readFile(
          filePath,
          options as { encoding: "utf8" },
        )) as typeof fs.readFileSync;
  try {
    assert.throws(
      () =>
        migrateBuiltInTemplate({
          templateId: "example",
          rootDirectory: fixture.root,
          apply: true,
          write: () => {},
        }),
      /Duplicate section ID/,
    );
  } finally {
    fs.readdirSync = readDirectory;
    fs.readFileSync = readFile;
  }
  assert.equal(fs.existsSync(fixture.sourceDirectory), true);
  assert.equal(fs.existsSync(fixture.libraryDirectory), false);
});

test("when source or destination validation fails then it changes no files", (t) => {
  const cases: ValidationCase[] = [
    {
      name: "a required file is missing",
      setup: (fixture) =>
        fs.rmSync(path.join(fixture.sourceDirectory, "template.json")),
      error: /missing/,
    },
    {
      name: "a component directory is nested",
      setup: (fixture) =>
        fs.mkdirSync(
          path.join(fixture.sourceDirectory, "components", "shared"),
        ),
      error: /Nested component directories/,
    },
    {
      name: "a component imports outside the component directory",
      components: {
        "Hero.tsx":
          'import { value } from "../shared";\nexport const Hero = () => <div>{value}</div>;\n',
      },
      error: /Relative import leaves/,
    },
    {
      name: "a component already exports config",
      components: {
        "Hero.tsx":
          "export const Hero = () => <div />;\nexport const config = {};\n",
      },
      error: /already exports config/,
    },
    {
      name: "a component lacks its matching named export",
      components: { "Hero.tsx": "export const Other = () => <div />;\n" },
      error: /must have a named export/,
    },
    {
      name: "the metadata JSON is invalid",
      setup: (fixture) =>
        fs.writeFileSync(
          path.join(fixture.sourceDirectory, "template.json"),
          "{",
        ),
      error: /Could not read legacy template metadata/,
    },
    {
      name: "the default layout references a missing section",
      layout: {
        content: [
          { type: "Missing", props: {} },
          { type: "MainContent", props: {} },
        ],
      },
      error: /references missing section Missing/,
    },
    {
      name: "the destination already has a real library",
      libraryFiles: { "library.json": "{}\n" },
      error: /destination is not fresh/,
    },
  ];

  for (const testCase of cases) {
    const fixture = createFixture(testCase);
    t.after(() => removeFixture(fixture));
    testCase.setup?.(fixture);

    assert.throws(
      () =>
        migrateBuiltInTemplate({
          templateId: "example",
          rootDirectory: fixture.root,
          apply: true,
          write: () => {},
        }),
      testCase.error,
      testCase.name,
    );
    assert.equal(fs.existsSync(fixture.sourceDirectory), true, testCase.name);
    assert.equal(
      fs.existsSync(path.join(fixture.libraryDirectory, "layouts", "example")),
      false,
      testCase.name,
    );
  }
});

test("when the Café and Coffee Shop template is inspected then it remains unchanged", () => {
  const starterRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
  );
  const cafeDirectory = path.join(
    starterRoot,
    "src",
    "registry",
    "yext-cafe-and-coffee-shop",
  );
  const templatePath = path.join(cafeDirectory, "template.json");
  const original = fs.readFileSync(templatePath, "utf8");

  assert.equal(
    fs.existsSync(path.join(cafeDirectory, "defaultLayout.json")),
    true,
  );
  assert.equal(
    fs
      .readdirSync(path.join(cafeDirectory, "components"))
      .filter((name) => name.endsWith(".tsx")).length > 0,
    true,
  );
  assert.equal(fs.readFileSync(templatePath, "utf8"), original);
});
