import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const GENERATED_FILE_PREFIX =
  "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */";
const TODO_DISPLAY_NAME = "TODO: Add a display name.";
const TODO_DESCRIPTION = "TODO: Add a description.";
const TODO_PREVIEW_IMAGE_URL = "TODO: Add a preview image URL.";
const TODO_VERTICAL = "TODO: Choose one vertical.";
const TODO_PURPOSE = "TODO: Choose one purpose.";
const TODO_SECTION_DISPLAY_NAME = "TODO: Add a section display name.";
const TODO_SECTION_DESCRIPTION = "TODO: Add a section description.";

type ComponentSource = {
  id: string;
  sourcePath: string;
  content: string;
};

type LegacyTemplate = {
  templateId: string;
  metadata: Record<string, unknown>;
  defaultLayout: Record<string, unknown>;
  components: ComponentSource[];
};

type MigrationOptions = {
  templateId: string;
  apply: boolean;
  rootDirectory?: string;
  write?: (message: string) => void;
};

type ParsedArguments =
  { help: true } | { help: false; templateId: string; apply: boolean };

/**
 * Converts one flat legacy built-in template into a fresh Section Library.
 *
 * Overview:
 * 1. Validate the legacy template and its empty destination without writing files.
 * 2. Build the Section Library files and report the required manual review work.
 * 3. When requested, write the complete library before removing the legacy source.
 */
export const migrateBuiltInTemplate = ({
  templateId,
  apply,
  rootDirectory = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
  ),
  write = console.log,
}: MigrationOptions): void => {
  if (!/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(templateId)) {
    throw new Error(`Template ID is not valid: ${templateId}`);
  }
  const sourceDirectory = path.join(
    rootDirectory,
    "src",
    "registry",
    templateId,
  );
  const libraryDirectory = path.join(rootDirectory, "src", "library");
  const source = readLegacyTemplate(sourceDirectory, templateId);
  validateLibraryDestination(libraryDirectory);
  const files = buildSectionLibraryFiles(source, templateId);

  writeReport({ sourceDirectory, libraryDirectory, source, apply, write });
  if (!apply) {
    return;
  }

  const temporaryDirectory = fs.mkdtempSync(
    path.join(path.dirname(libraryDirectory), ".section-library-migration-"),
  );
  try {
    writeFiles(temporaryDirectory, files);
    fs.rmSync(libraryDirectory, { recursive: true, force: true });
    fs.renameSync(temporaryDirectory, libraryDirectory);
  } catch (error) {
    fs.rmSync(temporaryDirectory, { recursive: true, force: true });
    throw error;
  }

  try {
    fs.rmSync(sourceDirectory, { recursive: true });
  } catch (error) {
    write(
      `The new Section Library was created, but the legacy source remains at ${sourceDirectory}: ${getErrorMessage(error)}`,
    );
    return;
  }
  write(`Created ${libraryDirectory} and removed ${sourceDirectory}.`);
};

const readLegacyTemplate = (
  sourceDirectory: string,
  templateId: string,
): LegacyTemplate => {
  const metadataPath = path.join(sourceDirectory, "template.json");
  const defaultLayoutPath = path.join(sourceDirectory, "defaultLayout.json");
  const componentsDirectory = path.join(sourceDirectory, "components");
  for (const requiredPath of [
    metadataPath,
    defaultLayoutPath,
    componentsDirectory,
  ]) {
    if (!fs.existsSync(requiredPath)) {
      throw new Error(`Legacy template is missing ${requiredPath}`);
    }
  }
  if (!fs.statSync(componentsDirectory).isDirectory()) {
    throw new Error(
      `Legacy components path is not a directory: ${componentsDirectory}`,
    );
  }

  const entries = fs.readdirSync(componentsDirectory, { withFileTypes: true });
  const nestedDirectory = entries.find((entry) => entry.isDirectory());
  if (nestedDirectory) {
    throw new Error(
      `Nested component directories are not supported: ${path.join(componentsDirectory, nestedDirectory.name)}`,
    );
  }
  const componentPaths = entries
    .filter((entry) => entry.isFile() && path.extname(entry.name) === ".tsx")
    .map((entry) => path.join(componentsDirectory, entry.name))
    .sort((left, right) => left.localeCompare(right));
  if (componentPaths.length === 0) {
    throw new Error(
      `Legacy template has no .tsx components: ${componentsDirectory}`,
    );
  }

  const components = componentPaths.map((sourcePath) => ({
    id: path.basename(sourcePath, ".tsx"),
    sourcePath,
    content: fs.readFileSync(sourcePath, "utf8"),
  }));
  const componentIds = new Set<string>();
  for (const component of components) {
    const canonicalId = component.id.toLocaleLowerCase();
    if (componentIds.has(canonicalId)) {
      throw new Error(`Duplicate section ID: ${component.id}`);
    }
    componentIds.add(canonicalId);
  }
  for (const component of components) {
    validateComponentSource(
      component.content,
      component.sourcePath,
      component.id,
      componentsDirectory,
    );
  }

  const metadata = readJson(metadataPath, "legacy template metadata");
  const defaultLayout = readJson(defaultLayoutPath, "legacy default layout");
  if (!isRecord(metadata)) {
    throw new Error(
      `Legacy template metadata must be an object: ${metadataPath}`,
    );
  }
  if (!isRecord(defaultLayout)) {
    throw new Error(
      `Legacy default layout must be an object: ${defaultLayoutPath}`,
    );
  }
  validateLayoutReferences(defaultLayout, componentIds, defaultLayoutPath);
  return { templateId, metadata, defaultLayout, components };
};

const validateComponentSource = (
  content: string,
  sourcePath: string,
  id: string,
  componentsDirectory: string,
): void => {
  const namedExport = new RegExp(
    `export\\s+(?:async\\s+)?(?:const|function|class)\\s+${escapeRegExp(id)}\\b|export\\s*\\{[^}]*\\b${escapeRegExp(id)}\\b[^}]*\\}`,
  );
  if (!namedExport.test(content)) {
    throw new Error(`Section ${id} must have a named export in ${sourcePath}`);
  }
  if (
    /export\s+(?:const|let|var|function|class)\s+config\b|export\s*\{[^}]*\bconfig\b[^}]*\}/.test(
      content,
    )
  ) {
    throw new Error(`Section ${id} already exports config: ${sourcePath}`);
  }

  for (const match of content.matchAll(
    /(?:import|export)\s+(?:type\s+)?(?:[^"']+?\s+from\s+)?["']([^"']+)["']/g,
  )) {
    const specifier = match[1];
    if (!specifier.startsWith(".")) {
      continue;
    }
    const resolvedPath = path.resolve(path.dirname(sourcePath), specifier);
    if (
      resolvedPath !== componentsDirectory &&
      !resolvedPath.startsWith(`${componentsDirectory}${path.sep}`)
    ) {
      throw new Error(
        `Relative import leaves the legacy components directory: ${sourcePath} imports ${specifier}`,
      );
    }
  }
};

const validateLayoutReferences = (
  value: unknown,
  componentIds: Set<string>,
  sourcePath: string,
): void => {
  if (Array.isArray(value)) {
    for (const item of value) {
      validateLayoutReferences(item, componentIds, sourcePath);
    }
    return;
  }
  if (!isRecord(value)) {
    return;
  }
  if (
    typeof value.type === "string" &&
    value.type !== "MainContent" &&
    !componentIds.has(value.type.toLocaleLowerCase())
  ) {
    throw new Error(
      `Default layout references missing section ${value.type}: ${sourcePath}`,
    );
  }
  for (const child of Object.values(value)) {
    validateLayoutReferences(child, componentIds, sourcePath);
  }
};

const validateLibraryDestination = (libraryDirectory: string): void => {
  if (!fs.existsSync(libraryDirectory)) {
    return;
  }
  const unsupportedPath = findRealLibraryPath(libraryDirectory);
  if (unsupportedPath) {
    throw new Error(
      `Section Library destination is not fresh: ${unsupportedPath}. Use a starter without an installed library.`,
    );
  }
};

const findRealLibraryPath = (directory: string): string | undefined => {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.name === ".gitkeep" || entry.name === "README.md") {
      continue;
    }
    if (entry.name === ".generated" && entry.isDirectory()) {
      for (const generatedEntry of fs.readdirSync(entryPath, {
        withFileTypes: true,
      })) {
        if (
          !generatedEntry.isFile() ||
          !fs
            .readFileSync(path.join(entryPath, generatedEntry.name), "utf8")
            .startsWith(GENERATED_FILE_PREFIX)
        ) {
          return path.join(entryPath, generatedEntry.name);
        }
      }
      continue;
    }
    return entryPath;
  }
};

const buildSectionLibraryFiles = (
  source: LegacyTemplate,
  templateId: string,
): Map<string, string> => {
  const displayName = stringOrTodo(
    source.metadata.displayName,
    TODO_DISPLAY_NAME,
  );
  const description = stringOrTodo(
    source.metadata.description,
    TODO_DESCRIPTION,
  );
  const vertical = singleValueOrTodo(source.metadata.verticals, TODO_VERTICAL);
  const purpose = singleValueOrTodo(source.metadata.purposes, TODO_PURPOSE);
  const previewImageUrl = stringOrTodo(
    source.metadata.previewImageUrl,
    TODO_PREVIEW_IMAGE_URL,
  );
  const files = new Map<string, string>();
  files.set(
    "library.json",
    formatJson({ schemaVersion: 1, id: templateId, displayName, description }),
  );
  files.set(
    path.join("layouts", templateId, "metadata.json"),
    formatJson({
      id: templateId,
      displayName,
      previewImageUrl,
      vertical,
      purpose,
      pageSetType: "ENTITY",
    }),
  );
  files.set(
    path.join("layouts", templateId, "defaultLayout.json"),
    formatJson(source.defaultLayout),
  );
  for (const component of source.components) {
    files.set(
      path.join("sections", `${component.id}.tsx`),
      `import type { SectionConfig } from "@yext/visual-editor";\n\n${component.content.trimEnd()}\n\nexport const config: SectionConfig = {\n  displayName: "${TODO_SECTION_DISPLAY_NAME}",\n  description: "${TODO_SECTION_DESCRIPTION}",\n  pageSetTypes: ["ENTITY"],\n};\n`,
    );
  }
  return files;
};

const writeFiles = (
  libraryDirectory: string,
  files: Map<string, string>,
): void => {
  for (const [relativePath, content] of files) {
    const destinationPath = path.join(libraryDirectory, relativePath);
    fs.mkdirSync(path.dirname(destinationPath), { recursive: true });
    fs.writeFileSync(destinationPath, content);
  }
};

const writeReport = ({
  sourceDirectory,
  libraryDirectory,
  source,
  apply,
  write,
}: {
  sourceDirectory: string;
  libraryDirectory: string;
  source: LegacyTemplate;
  apply: boolean;
  write: (message: string) => void;
}): void => {
  write(
    apply
      ? "Applying Section Library conversion:"
      : "Dry run: no files changed.",
  );
  write(
    `  ${path.join(sourceDirectory, "template.json")} -> ${path.join(libraryDirectory, "library.json")}`,
  );
  write(
    `  ${path.join(sourceDirectory, "template.json")} -> ${path.join(libraryDirectory, "layouts", source.templateId, "metadata.json")}`,
  );
  write(
    `  ${path.join(sourceDirectory, "defaultLayout.json")} -> ${path.join(libraryDirectory, "layouts", source.templateId, "defaultLayout.json")}`,
  );
  for (const component of source.components) {
    write(
      `  ${component.sourcePath} -> ${path.join(libraryDirectory, "sections", `${component.id}.tsx`)}`,
    );
  }
  write(
    `  displayName: ${stringOrTodo(source.metadata.displayName, TODO_DISPLAY_NAME)}`,
  );
  write(
    `  description: ${stringOrTodo(source.metadata.description, TODO_DESCRIPTION)}`,
  );
  write(
    `  vertical: ${singleValueOrTodo(source.metadata.verticals, TODO_VERTICAL)}`,
  );
  write(
    `  purpose: ${singleValueOrTodo(source.metadata.purposes, TODO_PURPOSE)}`,
  );
  write("Manual follow-up work:");
  write("  - Replace all TODO metadata values.");
  write(
    "  - Review section display names, descriptions, categories, and page-set types.",
  );
  write(
    "  - Review preview site URLs and other legacy metadata that has no Section Library field.",
  );
  write(
    "  - Move shared code, styles, and assets before using a template that needs them.",
  );
};

const stringOrTodo = (value: unknown, todo: string): string =>
  typeof value === "string" && value.trim() ? value : todo;

const singleValueOrTodo = (value: unknown, todo: string): string =>
  Array.isArray(value) &&
  value.length === 1 &&
  typeof value[0] === "string" &&
  value[0].trim()
    ? value[0]
    : todo;

const readJson = (filePath: string, description: string): unknown => {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(
      `Could not read ${description} at ${filePath}: ${getErrorMessage(error)}`,
    );
  }
};

const formatJson = (value: unknown): string =>
  `${JSON.stringify(value, null, 2)}\n`;

const escapeRegExp = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === "object" && !Array.isArray(value);

const getErrorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

const parseArguments = (args: string[]): ParsedArguments => {
  let templateId: string | undefined;
  let apply = false;
  for (let index = 0; index < args.length; index += 1) {
    switch (args[index]) {
      case "--template":
        templateId = args[index + 1];
        index += 1;
        break;
      case "--apply":
        apply = true;
        break;
      case "--help":
      case "-h":
        return { help: true };
      default:
        throw new Error(`Unknown argument: ${args[index]}`);
    }
  }
  if (!templateId) {
    throw new Error("Missing required --template <templateId> argument.");
  }
  return { help: false, templateId, apply };
};

const printHelp = (): void => {
  console.log(`Usage: npm run migrate-built-in-template -- --template <templateId> [--apply]

Converts src/registry/<templateId> into a fresh src/library Section Library.
The destination must have no real library. The conversion uses ENTITY for the layout and all sections.
Review all TODO metadata before use. Without --apply, the script only reports the conversion.`);
};

const main = (): void => {
  try {
    const options = parseArguments(process.argv.slice(2));
    if (options.help) {
      printHelp();
      return;
    }
    migrateBuiltInTemplate(options);
  } catch (error) {
    console.error(`Conversion failed: ${getErrorMessage(error)}`);
    process.exitCode = 1;
  }
};

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main();
}
