/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */
import type { Config } from "@puckeditor/core";
import { NikeDirectTier as NikeComponentNikeDirectTier } from "./components/NikeDirectTier";
import { NikeFooterPlaceholder as NikeComponentNikeFooterPlaceholder } from "./components/NikeFooterPlaceholder";
import { NikeHouseOfInnovationTier as NikeComponentNikeHouseOfInnovationTier } from "./components/NikeHouseOfInnovationTier";
import { NikePartnerTier as NikeComponentNikePartnerTier } from "./components/NikePartnerTier";
import { NikePilotTier as NikeComponentNikePilotTier } from "./components/NikePilotTier";
import { NikeStoreHeader as NikeComponentNikeStoreHeader } from "./components/NikeStoreHeader";
import { NikeUniteTier as NikeComponentNikeUniteTier } from "./components/NikeUniteTier";
export const NikeConfig: Config = {
  components: {
    NikeDirectTier: NikeComponentNikeDirectTier,
    NikeFooterPlaceholder: NikeComponentNikeFooterPlaceholder,
    NikeHouseOfInnovationTier: NikeComponentNikeHouseOfInnovationTier,
    NikePartnerTier: NikeComponentNikePartnerTier,
    NikePilotTier: NikeComponentNikePilotTier,
    NikeStoreHeader: NikeComponentNikeStoreHeader,
    NikeUniteTier: NikeComponentNikeUniteTier,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "NikeDirectTier",
        "NikeFooterPlaceholder",
        "NikeHouseOfInnovationTier",
        "NikePartnerTier",
        "NikePilotTier",
        "NikeStoreHeader",
        "NikeUniteTier",
      ],
    },
    other: {
      title: "Other",
      visible: false,
      components: [],
    },
  },
};
