/** THIS FILE IS AUTOGENERATED BY scripts/generateTemplateConfig.mjs */
import type { Config } from "@puckeditor/core";

import YetiComponentYetiCustomizeBannerSection from "./components/YetiCustomizeBannerSection";
import YetiComponentYetiExploreStoreSection from "./components/YetiExploreStoreSection";
import YetiComponentYetiFaqSection from "./components/YetiFaqSection";
import YetiComponentYetiFooterSection from "./components/YetiFooterSection";
import YetiComponentYetiHeaderSection from "./components/YetiHeaderSection";
import YetiComponentYetiHeroSection from "./components/YetiHeroSection";
import YetiComponentYetiHoursLocationSection from "./components/YetiHoursLocationSection";
import YetiComponentYetiReservationBannerSection from "./components/YetiReservationBannerSection";

export const mainConfig: Config = {
  components: {
    YetiCustomizeBannerSection: YetiComponentYetiCustomizeBannerSection,
    YetiExploreStoreSection: YetiComponentYetiExploreStoreSection,
    YetiFaqSection: YetiComponentYetiFaqSection,
    YetiFooterSection: YetiComponentYetiFooterSection,
    YetiHeaderSection: YetiComponentYetiHeaderSection,
    YetiHeroSection: YetiComponentYetiHeroSection,
    YetiHoursLocationSection: YetiComponentYetiHoursLocationSection,
    YetiReservationBannerSection: YetiComponentYetiReservationBannerSection,
  },
  categories: {
    components: {
      title: "Components",
      components: [
        "YetiCustomizeBannerSection",
        "YetiExploreStoreSection",
        "YetiFaqSection",
        "YetiFooterSection",
        "YetiHeaderSection",
        "YetiHeroSection",
        "YetiHoursLocationSection",
        "YetiReservationBannerSection",
      ],
    },
  },
};

export default mainConfig;
