/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */
import type { Config } from "@puckeditor/core";
import { mainConfig, type MainConfigProps } from "@yext/visual-editor";
import { YextDeepCurrentAdvisors as YextDeepCurrentComponentYextDeepCurrentAdvisors } from "./components/yext-DeepCurrentAdvisors";
import { YextDeepCurrentBanner as YextDeepCurrentComponentYextDeepCurrentBanner } from "./components/yext-DeepCurrentBanner";
import { YextDeepCurrentBreadcrumbs as YextDeepCurrentComponentYextDeepCurrentBreadcrumbs } from "./components/yext-DeepCurrentBreadcrumbs";
import { YextDeepCurrentDetails as YextDeepCurrentComponentYextDeepCurrentDetails } from "./components/yext-DeepCurrentDetails";
import { YextDeepCurrentEvents as YextDeepCurrentComponentYextDeepCurrentEvents } from "./components/yext-DeepCurrentEvents";
import { YextDeepCurrentFaqs as YextDeepCurrentComponentYextDeepCurrentFaqs } from "./components/yext-DeepCurrentFaqs";
import { YextDeepCurrentFeaturedServices as YextDeepCurrentComponentYextDeepCurrentFeaturedServices } from "./components/yext-DeepCurrentFeaturedServices";
import { YextDeepCurrentFooter as YextDeepCurrentComponentYextDeepCurrentFooter } from "./components/yext-DeepCurrentFooter";
import { YextDeepCurrentHeader as YextDeepCurrentComponentYextDeepCurrentHeader } from "./components/yext-DeepCurrentHeader";
import { YextDeepCurrentHero as YextDeepCurrentComponentYextDeepCurrentHero } from "./components/yext-DeepCurrentHero";
import { YextDeepCurrentNearbyLocations as YextDeepCurrentComponentYextDeepCurrentNearbyLocations } from "./components/yext-DeepCurrentNearbyLocations";
import { YextDeepCurrentPhotoGallery as YextDeepCurrentComponentYextDeepCurrentPhotoGallery } from "./components/yext-DeepCurrentPhotoGallery";
import { YextDeepCurrentResources as YextDeepCurrentComponentYextDeepCurrentResources } from "./components/yext-DeepCurrentResources";
import { YextDeepCurrentReviews as YextDeepCurrentComponentYextDeepCurrentReviews } from "./components/yext-DeepCurrentReviews";
import { YextDeepCurrentStaticMap as YextDeepCurrentComponentYextDeepCurrentStaticMap } from "./components/yext-DeepCurrentStaticMap";
import { YextDeepCurrentStory as YextDeepCurrentComponentYextDeepCurrentStory } from "./components/yext-DeepCurrentStory";
import { YextDeepCurrentTestimonials as YextDeepCurrentComponentYextDeepCurrentTestimonials } from "./components/yext-DeepCurrentTestimonials";
import { YextDeepCurrentVideo as YextDeepCurrentComponentYextDeepCurrentVideo } from "./components/yext-DeepCurrentVideo";
type GeneratedYextDeepCurrentConfigProps = Pick<MainConfigProps, "MainContent"> & {
  "YextDeepCurrentAdvisors": any;
  "YextDeepCurrentBanner": any;
  "YextDeepCurrentBreadcrumbs": any;
  "YextDeepCurrentDetails": any;
  "YextDeepCurrentEvents": any;
  "YextDeepCurrentFaqs": any;
  "YextDeepCurrentFeaturedServices": any;
  "YextDeepCurrentFooter": any;
  "YextDeepCurrentHeader": any;
  "YextDeepCurrentHero": any;
  "YextDeepCurrentNearbyLocations": any;
  "YextDeepCurrentPhotoGallery": any;
  "YextDeepCurrentResources": any;
  "YextDeepCurrentReviews": any;
  "YextDeepCurrentStaticMap": any;
  "YextDeepCurrentStory": any;
  "YextDeepCurrentTestimonials": any;
  "YextDeepCurrentVideo": any;
};
export const YextDeepCurrentConfig: Config<GeneratedYextDeepCurrentConfigProps> = {
  components: {
    "MainContent": mainConfig.components.MainContent,
    "YextDeepCurrentAdvisors": YextDeepCurrentComponentYextDeepCurrentAdvisors,
    "YextDeepCurrentBanner": YextDeepCurrentComponentYextDeepCurrentBanner,
    "YextDeepCurrentBreadcrumbs": YextDeepCurrentComponentYextDeepCurrentBreadcrumbs,
    "YextDeepCurrentDetails": YextDeepCurrentComponentYextDeepCurrentDetails,
    "YextDeepCurrentEvents": YextDeepCurrentComponentYextDeepCurrentEvents,
    "YextDeepCurrentFaqs": YextDeepCurrentComponentYextDeepCurrentFaqs,
    "YextDeepCurrentFeaturedServices": YextDeepCurrentComponentYextDeepCurrentFeaturedServices,
    "YextDeepCurrentFooter": YextDeepCurrentComponentYextDeepCurrentFooter,
    "YextDeepCurrentHeader": YextDeepCurrentComponentYextDeepCurrentHeader,
    "YextDeepCurrentHero": YextDeepCurrentComponentYextDeepCurrentHero,
    "YextDeepCurrentNearbyLocations": YextDeepCurrentComponentYextDeepCurrentNearbyLocations,
    "YextDeepCurrentPhotoGallery": YextDeepCurrentComponentYextDeepCurrentPhotoGallery,
    "YextDeepCurrentResources": YextDeepCurrentComponentYextDeepCurrentResources,
    "YextDeepCurrentReviews": YextDeepCurrentComponentYextDeepCurrentReviews,
    "YextDeepCurrentStaticMap": YextDeepCurrentComponentYextDeepCurrentStaticMap,
    "YextDeepCurrentStory": YextDeepCurrentComponentYextDeepCurrentStory,
    "YextDeepCurrentTestimonials": YextDeepCurrentComponentYextDeepCurrentTestimonials,
    "YextDeepCurrentVideo": YextDeepCurrentComponentYextDeepCurrentVideo,
  },
  categories: {
  "structure": {
    "components": [
      "MainContent"
    ],
    "visible": false,
    "title": "Structure"
  },
  "components": {
    "title": "Components",
    "components": [
      "YextDeepCurrentAdvisors",
      "YextDeepCurrentBanner",
      "YextDeepCurrentBreadcrumbs",
      "YextDeepCurrentDetails",
      "YextDeepCurrentEvents",
      "YextDeepCurrentFaqs",
      "YextDeepCurrentFeaturedServices",
      "YextDeepCurrentFooter",
      "YextDeepCurrentHeader",
      "YextDeepCurrentHero",
      "YextDeepCurrentNearbyLocations",
      "YextDeepCurrentPhotoGallery",
      "YextDeepCurrentResources",
      "YextDeepCurrentReviews",
      "YextDeepCurrentStaticMap",
      "YextDeepCurrentStory",
      "YextDeepCurrentTestimonials",
      "YextDeepCurrentVideo"
    ]
  },
  "other": {
    "title": "Other",
    "visible": false,
    "components": []
  }
},
};