name: 'Create dev release branch'

on:
  repository_dispatch:
    types: [dev-release-created]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout main branch as the base'
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: 'Create new branch from PR number'
        env:
          BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
        run: git checkout -b "$BRANCH_NAME"

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install feature dependency using pkg.pr.new'
        # This installs the visual-editor dev release from the specified PR using pkg.pr.new
        env:
          PACKAGE_URL: ${{ github.event.client_payload.package_url }}
        run: |
          echo "Installing package from: $PACKAGE_URL"
          npm install --force "$PACKAGE_URL"
          echo "Package installed successfully"

      - name: 'Commit and push the new branch'
        env:
          PR_NUMBER: ${{ github.event.client_payload.pr_number }}
          PR_TITLE: ${{ github.event.client_payload.pr_title }}
          BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: update visual-editor for PR #$PR_NUMBER - $PR_TITLE"
          git push --set-upstream origin "$BRANCH_NAME" 