name: 'Create dev release branch'

on:
  repository_dispatch:
    types: [dev-release-created]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Extract data from payload'
        id: payload
        run: |
          echo "branch_name=${{ github.event.client_payload.branch_name }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.client_payload.pr_number }}" >> $GITHUB_OUTPUT
          echo "pr_title=${{ github.event.client_payload.pr_title }}" >> $GITHUB_OUTPUT
          echo "pr_url=${{ github.event.client_payload.pr_url }}" >> $GITHUB_OUTPUT
          echo "author=${{ github.event.client_payload.author }}" >> $GITHUB_OUTPUT
          echo "package_url=${{ github.event.client_payload.package_url }}" >> $GITHUB_OUTPUT

      - name: 'Checkout main branch as the base'
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: 'Create new branch from PR number'
        run: git checkout -b ${{ steps.payload.outputs.branch_name }}

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install feature dependency using pkg.pr.new'
        # This installs the visual-editor dev release from the specified PR using pkg.pr.new
        run: |
          echo "Installing package from: ${{ steps.payload.outputs.package_url }}"
          npm install --force ${{ steps.payload.outputs.package_url }}
          echo "Package installed successfully"

      - name: 'Commit and push the new branch'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: update visual-editor for PR #${{ steps.payload.outputs.pr_number }} - ${{ steps.payload.outputs.pr_title }}"
          git push --set-upstream origin ${{ steps.payload.outputs.branch_name }} 