name: 'Create dev release branch'

on:
  repository_dispatch:
    types: [dev-release-created]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout main branch as the base'
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: 'Create new branch from PR number'
        env:
          BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
        run: |
          # Check if branch already exists remotely
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "Branch $BRANCH_NAME already exists, checking it out and pulling latest"
            git fetch origin "$BRANCH_NAME"
            git checkout "$BRANCH_NAME"
            git pull origin "$BRANCH_NAME"
          else
            echo "Creating new branch $BRANCH_NAME"
            git checkout -b "$BRANCH_NAME"
          fi

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install feature dependency using pkg.pr.new'
        # This installs the visual-editor dev release from the specified PR using pkg.pr.new
        env:
          PACKAGE_URL: ${{ github.event.client_payload.package_url }}
        run: |
          echo "Installing package from: $PACKAGE_URL"
          npm install --force "$PACKAGE_URL"
          echo "Package installed successfully"

      - name: 'Commit and push the new branch'
        env:
          PR_NUMBER: ${{ github.event.client_payload.pr_number }}
          PR_TITLE: ${{ github.event.client_payload.pr_title }}
          BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "feat: update visual-editor for PR #$PR_NUMBER - $PR_TITLE"
            git push origin "$BRANCH_NAME"
          fi 